### ISSUE TITLE
Automatically rename .cue files to use disc ID

### ISSUE THREAD

**Issue by GMMan** [pathartl/BleemSync#298] opened 2019-01-28 23:25 UTC
Because of the way region detection works in Sony's PCSX, any game where the .cue file has `P` as the third letter of the filename causes the emulator to load the Japanese BIOS, which tends to break non-Japanese region games. BlemSync should automatically rename the uploaded .cue according to the disc ID so the correct BIOS is loaded.

**Comment by GMMan** [comment] 2019-01-29 00:51
We can revert Sony's patch for region detection and use PCSX's original logic if we are always going to overmount the stock PCSX.

**Comment by patrickmollohan** [comment] 2019-01-31 05:08
As an outsider, I agree with @pathartl. It is much easier to read what games are what in file browsers when games are named by title (or whatever the user sets it to) as opposed to serial. Plus, Sony's configurations should be bent to the end user, not the other way around.

**Comment by GMMan** [comment] 2019-01-31 05:14
It's still to be determined whether the game folder is supposed to be somewhere users should be poking around in. And most naming of files aren't ideal for a Linux-based environment (spaces, capitalization, etc.).

**Comment by patrickmollohan** [comment] 2019-01-31 05:50
With all due respect, that reasoning is a bit confining. There shouldn't really be a reason why the user can't be allowed in the folder (to do things like browsing via RetroArch to launch a game, backing up/editing save states/config files, using their flash drives on other systems like a Pi, etc) . I understand that it's a wee less convenient to make sure everything is properly escaped or quoted in the code, but it seems like a regression to take away user freedoms and to change what the user wants to do just because Sony didn't get it right. For that matter, no reason why manually adding games shouldn't be supported, or that the folder structures have to conform to the numbering scheme. It is less convenient to manually add games, granted, but line 151 of "0050_bleemsync.funcs" checks to see if the number of folders match the number of games in the database. Instead of printing out an error in the logs that no one will read, call a function there to recreate the databases. At the end of the day, I love and appreciate everything that has been done with this project, but I tend to prefer when users have options as opposed to restrictions.

**Comment by GMMan** [comment] 2019-01-31 05:57
It's not a simple matter of rescan and regenerate right now. That was <1.0 and somewhat annoyingly slow. We have a database for the UI, and a database the stock UI will use, and both of those will have to be updated in sync. Trying to support arbitrary user modifications will take some work, which is why whether the user should be allowed to mess with the games folder is TBD.

**Comment by patrickmollohan** [comment] 2019-01-31 21:32
I know that it isn't that simple right now, but it could be. The rescan and regen code only needs to be executed in that if statement on line 151 as I mentioned, which would only happen if there is a discrepancy between the number of games in the database and the number of games in the folder. Otherwise, there is no need to run the regen code, and the boot times will be exactly the same. I know there are issues with making sure both databases are in sync (perhaps that's a sign that it is getting more convoluted than it should be; no reason to use more than one database anyway). It can be fixed and simplified. Creating such restrictions only ensures that later on down the road, there will be more problems. Code that is written to be rigid and inflexible just because it is more convenient to write is not a good way of programming. You have to expect that end users will mess with files, and for the most part, BleemSync does. The if statements are already in place. It would just take maybe 10% more to do it right rather than support bad decisions and complacency.

**Comment by pathartl** [comment] 2019-01-31 21:48
BleemSync's model is going to closely follow that of iTunes. Automatic scanning of the disk for new games is currently a nice-to-have and is certainly not on the minds of the team at this time in particular.

The reality is depending on what system the games are being synced to, files may need to be renamed to or modified fit certain restrictions, similar to how when syncing an iPod with iTunes usually results in a directory of a bunch of randomly-named files and folders. While I'm not sure we have to go this far, I certainly see the benefits of this solution.

To make things easiest for the user, at this time we just can't implement a half assed solution. Achievements like implementing multiple game uploads and desktop-side UI directly benefits the user while allowing us to stay within our constraints. Allowing people to manage files on their drive is essentially developing another UX which introduces a whole other set of requirements, parameters, expectations, etc.

Going back to the original issue, would it make sense to implement an interface for creating `pcsx.cfg` files on a per game basis? This would resolve a few other issues and would allow us to set which BIOS to use.

**Comment by GMMan** [comment] 2019-01-31 21:51
Sure, if we can set certain PCSX settings from BSUI, that'd be great. Just need to back out some of Sony's changes so the settings aren't being ignored.

**Comment by pathartl** [comment] 2019-01-31 22:06
Closing this in favor of a new issue.

**Closed by pathartl** 2019-01-31 22:06 UTC
Labels: enhancement
