### ISSUE TITLE
Games load fine but system shuts down after leaving a game.

### ISSUE THREAD

**Issue by Sloneborg** [pathartl/BleemSync#103] opened 2018-12-19 04:29 UTC
I am using 4.1 with a SanDisk cruzer fit 64gb with around 81 games on it. The games load up and play fine but as soon as I exit out of a game it goes back to the game select and shuts off. Just trying to see if it's a common problem and any ideas of a fix.

**Comment by khenzel** [comment] 2018-12-19 09:21
This happens for me too, but only when i have my drive loaded with around 300 titles. Doesn't seem to happen on my device with around 150 titles.

**Comment by FyreAnt** [comment] 2018-12-20 06:06
Yea, mine got corrupted somehow. I rebuilt the database and pulled the system pre file booted it up and reinitialized and its back to booting the way it should off the stick. I reduced the game count to 60 and it still shuts off after exiting a game. When I booted the system with 32 games on it, it does not power off after exiting a game. There must be a specific amount of games or total game folder size that trips it.

**Comment by blacksunfox** [comment] 2018-12-21 09:19
SOLVED :)
1. go to games folder and in "search" write ".pcsx".
2. If you have for example 60 games you will see 60 folders and 60 config file with the ".pcsx" word inside (they are config file and folder in every single game)...in this example you will delete 60 files + 60 folders (120 total).
3. Take the "virgin" .pcsx file from the folder games/ 1 / gamedata / ...directly from the .zip file of bleemsync 0.4.1 And copy it.
4. Paste it insiede every gamedata folder of every game (60 paste in this example)
5. Delete all the folder but not the games folder from you usb "SONY"
6.  Open the bleemsync 0.4.1 zip file and copy all the folder in your usb SONY but dont copy the games folder
7. Use bleemsync to sync
8. Enjoy your mod that dont crash again when you reset.
 
The issue is something that happen using psxtool or other tools for sort it a/z because whem the tools do it create some issue in config files.

**Comment by FyreAnt** [comment] 2018-12-21 20:53
Tried your solution - Followed the steps perfectly. Does not solve the issue.

**Comment by blacksunfox** [comment] 2018-12-21 20:56
I m sad about that...i hope the next update will resolve this problem for
everyone.

Il giorno ven 21 dic 2018, 21:53 FyreAnt <notifications@github.com> ha
scritto:

**Comment by Player1Login** [comment] 2018-12-22 04:47
Solved reply didn’t work for me either and deleted my saves ahh. Thanks for trying to help though hopefully this issue is patched soon!

**Comment by Player1Login** [comment] 2018-12-22 04:50
Pathartl this is happening for me too I have 100+ on a 64gb San disk cruzer glide. Is this being addressed? Honestly this is my only issue with bleemsync

**Comment by BoscoTheMan82** [comment] 2018-12-23 03:43
Its related to your boxart, the images are too big. Scale them down to 226x226 then compress the png's using PNGGauntlet or PNGyu. This quickens up boot time as well.

**Comment by Player1Login** [comment] 2018-12-23 04:37
You sir are a gentleman and a scholar

**Comment by FyreAnt** [comment] 2018-12-23 04:39
I’m going to try this later. I have cover art that is a bit big

**Comment by Player1Login** [comment] 2018-12-23 06:37
Thanks Bosco! Can confirm this method works as long as the cover art is 500x500 or less the system shut down should be fixed!

**Comment by FyreAnt** [comment] 2018-12-23 07:54
I also can confirm that compressing all coverart solves the issue. I compressed all my cover art to 226x226 and have played 3 different games and closed out and went back to the menu no issue. Thanks for this!!

**Comment by Sloneborg** [comment] 2018-12-24 05:40
This worked for me also. It's running fantastic.

**Closed** 2018-12-24 15:33 UTC
