### ISSUE TITLE
Bleemsync v1.0.0

### ISSUE THREAD

**Issue by goemon78** [pathartl/BleemSync#265] opened 2019-01-27 06:29 UTC
Whenever I try to add an new game. I can run the adding process but when I turn my console on, There is just a transparent black square with the name of the game. It also will not start. What Am I doing wrong?

**Comment by TheGreenGoblin** [comment] 2019-01-27 07:14
Are you sure you added the artwork when you added the game? It's usually automatic, but not always.

**Comment by goemon78** [comment] 2019-01-27 09:10
In the programm it adds the art correctly. Everything looks like it is going fine. But when I boot up the ps classic. It shows all my original games and the ones I addes are black squares and will not start. Name of the game also shows correctly but it's a no go

**Comment by TheOlympian** [comment] 2019-01-27 14:07
Did you upload both bin and cue files of each game? Where did you get your games from?

**Comment by swingflip** [comment] 2019-01-28 15:58
Can you please upload the 3 log files once booting please

**Comment by goemon78** [comment] 2019-01-28 19:33
[bleemsync.log](https://github.com/pathartl/BleemSync/files/2804604/bleemsync.log)
[bleemsync_ui.log](https://github.com/pathartl/BleemSync/files/2804605/bleemsync_ui.log)
[bootloader.log](https://github.com/pathartl/BleemSync/files/2804606/bootloader.log)
[ui_menu.log](https://github.com/pathartl/BleemSync/files/2804607/ui_menu.log)

You mean these swingflip?
I did a migration install from bleemsync 0.4.1 Could this be the problem also?

**Comment by swingflip** [comment] 2019-01-29 17:23
[BLEEMSYNC](PROFILE) BleemSync tmpfs mounting took: 15ms to execute
[BLEEMSYNC](WARN) You have more folders in /media/games/ than are in the BleemSync database.
[BLEEMSYNC](WARN) Do not manually add games to this folder. Remove any manually created folders and add them via the BleemSync web interface.
[BLEEMSYNC](PROFILE) BleemSync tmpfs symbolic linking took: 486ms to execute


You have games in your games/ folder that doesn't exist in your regional.db Have you dragged games into that game folder? Does the number OF folders inside game match the number of games in the UI?

**Comment by swingflip** [comment] 2019-01-30 16:28
@goemon78 we will need a copy of your regional db and a screenshot of all the folders in your usb:/games/ folder.

The regional.db is in USB:/bleemsync/etc/bleemsync/SYS/databases/

@andshrew will be the best person to review as he did the migration method

**Comment by cnterr** [comment] 2019-01-31 07:33
I also had this problem in the past with the 0.4.1, remained even after the migration. In my case the problem was caused by the commas present in the file name of the redump collection (Ex. "Title (Europe) (En,De,It)"), in the game.ini file the commas separated the various discs for this reason the game was considered a multidisk but obviously with wrong names. I simply replaced the commas with the spaces.

**Comment by goemon78** [comment] 2019-01-31 17:31
How do I upload my regional.db file. This forum does not allow it that easily

**Comment by goemon78** [comment] 2019-01-31 17:31
![naamloos](https://user-images.githubusercontent.com/46196679/52072932-7927af00-2586-11e9-91e7-4ecacd0e3c6f.jpg)

**Comment by goemon78** [comment] 2019-01-31 17:32
here is my games folder

**Comment by Veund** [comment] 2019-02-08 11:27
I had this issue, apparently there is a bug where if your bin and cue files are in caps this happens, changing them to lower case and updating the cue file fixed this for me, the bug is fixed in the next hot fix update

**Closed** 2020-02-19 02:27 UTC
Labels: bug, needs review
