### ISSUE TITLE
BleemSync Unix executable doesn't work on Mac. 

### ISSUE THREAD

**Issue by renordico** [pathartl/BleemSync#138] opened 2018-12-26 23:00 UTC
I've downloaded the latest version of BleemSync (0.4.1) for OSX and when the games folders are ready I open the BleemSync Unix executable, but this is what cames out:

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/Users/username/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

I tried to open the terinal and open the same file writing "CD" and then paste the file, but it still doesn't work. 

the 0.3.2 version worked fine.

**Comment by pathartl** [comment] 2018-12-27 00:00
Dupe of #73 and #81

**Closed by pathartl** 2018-12-27 00:00 UTC
