### ISSUE TITLE
Issues will 1.0 and file extensions 

### ISSUE THREAD

**Issue by Veund** [pathartl/BleemSync#319] opened 2019-02-04 09:49 UTC
I have found that if the fie extension is in caps the ps clasic sees the imge as a transparent square and refuses to play the game if its lower case its fine, this is annoying as programs like img burn default to caps

**Comment by andshrew** [comment] 2019-02-04 12:15
This is a duplicate of https://github.com/pathartl/BleemSync/issues/278

Fixed in the next hot fix release.

**Closed** 2019-02-04 12:15 UTC
Labels: duplicate
