### ISSUE TITLE
Is there any way to play 2-player?

### ISSUE THREAD

**Issue by abelogan** [pathartl/BleemSync#122] opened 2018-12-22 09:15 UTC
Is there any way to play 2-player?  Some sort of splitter or something?

**Comment by pahakalle** [comment] 2018-12-22 09:33
duplicate of #107

**Comment by Sanandreas21** [comment] 2018-12-22 16:39
You just need a USB hub, plug it into port 1 then both controllers into the hub.

I'm using a one that isn't externally powered and seems to work with both controllers.

**Closed** 2018-12-23 09:59 UTC
