### ISSUE TITLE
error bleemsync

### ISSUE THREAD

**Issue by roobster12** [pathartl/BleemSync#143] opened 2018-12-27 22:53 UTC
in the 0.3 version everything works, but the 0.4 isnt working at all... i always get this message.
can anybody help please?

the message:
<img width="1107" alt="schermafbeelding 2018-12-27 om 22 58 57" src="https://user-images.githubusercontent.com/46203949/50496760-966ed800-0a32-11e9-8303-46a82292bb8b.png">

**Comment by pathartl** [comment] 2018-12-27 22:56
Dupe of #81 and #73

**Closed by pathartl** 2018-12-27 22:56 UTC
