### ISSUE TITLE
BleemSync on Mac yields this message in Terminal: 'BleemSync.Config.json' was not found

### ISSUE THREAD

**Issue by thatpaulallen** [pathartl/BleemSync#148] opened 2018-12-28 17:10 UTC
I added a game to the games folder using the correct format, but when I try to click on BleemSyn.exe, Terminal comes back with the below, even though 'BleemSync.Config.json' is in the folder.

Last login: Thu Dec 27 19:57:19 on ttys000
MacBook-Air:~ paulallen$ /Users/paulallen/Downloads/BleemSync-0-2/BleemSync/BleemSync ; exit;

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'BleemSync.Config.json' was not found and is not optional. The physical path is '/Users/paulallen/BleemSync.Config.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at BleemSync.Program.Main(String[] args) in C:\data\repositories\BleemSync\BleemSync\Program.cs:line 20
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by thatpaulallen** [comment] 2018-12-28 17:22
I'm on a 2017 MacBook Air running MoJave

**Comment by pathartl** [comment] 2018-12-28 17:35
Dupe of #81 and #73

**Closed by pathartl** 2018-12-28 17:35 UTC
