### ISSUE TITLE
Enhancement Request: Ability to save emulator settings

### ISSUE THREAD

**Issue by LifesFailure** [pathartl/BleemSync#44] opened 2018-12-13 18:10 UTC
It would be nice to be able to save/commit emulator settings for when powering off and back on console to include NTSC region to fix games and scanlines. And/or create a secondary emulator settings config to be able to choose which to load upon launching or roll back if issues with changes made

**Comment by mtrivs** [comment] 2018-12-13 19:49
The ability to have per-game emulation settings would be ideal.   That way if you use certain settings that improve performance for a particular game, you can save them to the game's folder, to be loaded the next time the game is executed from the menu.    If no game-specific emulation file is saved, then use the default emulation settings.   This is similar to the way this works for retroarch today.

**Comment by LifesFailure** [comment] 2018-12-13 20:04
I agree. This is a better option. Some games I would perhaps prefer not to play with scanlines or if changing region to NTSC for 60hz screws up a particular game.

**Comment by pathartl** [comment] 2018-12-13 20:10
Dupe of #43

**Closed by pathartl** 2018-12-13 20:10 UTC
