### ISSUE TITLE
Stock games still gone from 3.0

### ISSUE THREAD

**Issue by FreudienSlip** [pathartl/BleemSync#75] opened 2018-12-16 18:09 UTC
Hello, any news on a fix for the stock games not running after 3.0 took them? Not a big deal, since the usb works fine now, just curious.

69 games manually added, no problems. usb 3.1 fat32 64gb samsung the bar plus. I have quit through console button, through emulator exit, no issues. bleemsynv 3.2.
I found one issue where there were commas in the name of the actual game causing an issue with the png and ini files not working correctly for that game, renamed and no problems. No other issues.

**Comment by GforceMI69** [comment] 2018-12-17 21:57
Same issue here, I tried the fix that was posted for the lolhack + 0.3.0. and I still have the first 2 games missing after trying to add 2 games with 0.3.0, I try to play the game it switches to the save state slot and then does nothing other than if I repeatedly hit the X button I can see the console is trying to load up a 2 game menu with the 2 games that don't work.

all other stock games run fine etc, and the last try I had with Bleemsync was 0.3.1 and added games worked fine, not really a massive issue to lose those 2 games but would be nice to do a full restore of the console to originality when in use without the USB key.

**Comment by pathartl** [comment] 2018-12-19 18:15
Dupe of #64

**Closed by pathartl** 2018-12-19 18:15 UTC
Labels: duplicate
